propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  countingdata:
    _attributes: { phpName: Countingdata, idMethod: native }
    HALL: { phpName: Hall, type: VARCHAR, size: '3', required: true }
    OCCUPANCY: { phpName: Occupancy, type: INTEGER, required: true }
  modelcounts:
    _attributes: { phpName: Modelcounts, idMethod: native }
    count_time: { phpName: CountTime, type: TIMESTAMP, primaryKey: true, required: true }
    JAY: { phpName: Jay, type: INTEGER, required: false  }
    JJP: { phpName: Jjp, type: INTEGER, required: false  }
    FER: { phpName: Fer, type: INTEGER, required: false  }
  modelformula:
    _attributes: { phpName: Modelformula, idMethod: native }
    JAY: { phpName: Jay, type: DECIMAL, size: '8', scale: '6', required: true }
    FER: { phpName: Fer, type: DECIMAL, size: '8', scale: '6', required: true }
    JJP: { phpName: Jjp, type: DECIMAL, size: '8', scale: '6', required: true }
  nutrition:
    _attributes: { phpName: Nutrition, idMethod: native }
    FOOD_ID: { phpName: FoodId, type: SMALLINT, primaryKey: true, required: true }
    CURRENT: { phpName: Current, type: INTEGER, size: '1', required: false  }
    Dish: { phpName: Dish, type: VARCHAR, size: '50', required: false }
    JAY: { phpName: Jay, type: INTEGER, size: '1', required: false  }
    JJP: { phpName: Jjp, type: INTEGER, size: '1', required: false  }
    FER: { phpName: Fer, type: INTEGER, size: '1', required: false  }
    ServingSize: { phpName: Servingsize, type: VARCHAR, size: '20', required: false  }
    Calories: { phpName: Calories, type: INTEGER, size: '5', required: false  }
    TotalFat: { phpName: Totalfat, type: INTEGER, size: '5', required: false  }
    Cholesterol: { phpName: Cholesterol, type: INTEGER, size: '5', required: false  }
    SaturatedFat: { phpName: Saturatedfat, type: INTEGER, size: '5', required: false  }
    Protein: { phpName: Protein, type: INTEGER, size: '5', required: false  }
    Carbohydrate: { phpName: Carbohydrate, type: INTEGER, size: '5', required: false  }
    Fiber: { phpName: Fiber, type: INTEGER, size: '5', required: false  }
    Sodium: { phpName: Sodium, type: INTEGER, size: '5', required: false  }
    Score: { phpName: Score, type: INTEGER, size: '5', required: false  }
    Url: { phpName: Url, type: VARCHAR, size: '200', required: false  }
    V: { phpName: V, type: INTEGER, size: '1', required: false  }
    VN: { phpName: Vn, type: INTEGER, size: '1', required: false  }
    GF: { phpName: Gf, type: INTEGER, size: '1', required: false  }
    L: { phpName: L, type: INTEGER, size: '1', required: false  }
  testdata:
    _attributes: { phpName: Testdata, idMethod: native }
    HALL: { phpName: Hall, type: VARCHAR, size: '30', required: true }
    TTIME: { phpName: Ttime, type: VARCHAR, size: '30', required: false }
    MTYPE: { phpName: Mtype, type: VARCHAR, size: '20', required: false }
    ENTR: { phpName: Entr, type: INTEGER, required: false }
  user:
    User: { phpName: UserId, type: VARCHAR, size: '50', required: true }
    Name: { phpName: Name, type: VARCHAR, size: '50', required: false }
    Gender: { phpName: Gender, type: VARCHAR, size: '10', required: false }
    Food: { phpName: Food, type: VARCHAR, size: '50', required: false }
    Visits: { phpName: Visits, type: INTEGER, required: false, default: 0 }

